<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
<html>
	<head>
		<title>Project Voldemort</title>
		<link rel="stylesheet" href="style.css" type="text/css">
		<link rel="icon" type="image/png" href="http://project-voldemort.com/images/vold-logo-small.png">
		<meta name="keywords" content="Project Voldemort, Voldemort, key-value storage, distributed storage, Amazon Dynamo, persistence, scalability">
		<meta name="description" content="The web site for Project Voldemort, a distributed key-value storage system.">
		<meta http-equiv="Content-Type" content="text/html;charset=utf-8">
	</head>
	<body>
		<div>
			<div id="header" style="cursor: pointer;" onclick="location.href='http://project-voldemort.com';">
		  		<div class="title">
			     	Project Voldemort
			    </div>
			    <div class="subtitle">
					A distributed database
				</div>
			</div>
			<div class="lsidebar">
				<ul>
					<li>
						<a href="blog">blog</a>
					</li>
					<li>
						<a href="design.php">design</a>
					</li>
					<li>
						<a href="http://groups.google.com/group/project-voldemort">mailing list</a>
					</li>
					<li>
						<a href="http://github.com/voldemort/voldemort/downloads">releases</a>
					</li>
					<li>
						<a href="http://test.project-voldemort.com:8080/job/voldemort-master">snapshot build</a>
					</li>
					<li>
						<a href="configuration.php">configuration</a>
					</li>
					<li>
						<a href="/javadoc/client">client javadoc</a>
					</li>
					<li>
						<a href="/javadoc/all">all javadoc</a>
					</li>
					<li>
						<a href="quickstart.php">quickstart</a>
					</li>
					<li>
						<a href="developer.php">developer&nbsp;info</a>
					</li>
					<li>
						<a href="projects.php">fun&nbsp;projects</a>
					</li>
					<li>
						<a href="performance.php">performance</a>
					</li>
					<li>
					    <a href="http://test.project-voldemort.com:8080">unit tests</a>	
					</li>
					<li>
						<a href="http://github.com/voldemort/voldemort/tree/master">source</a>
					</li>
					<li>
						<a href="http://github.com/voldemort/voldemort/issues">bugs</a>
					</li>
				</ul>
			</div>
	
			<div class="content">
			