<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
<html>
	<head>
		<title>Project Voldemort</title>
		<link rel="stylesheet" href="style.css" type="text/css"/>
	</head>
	<body>
		<div>
			<div id="header" style="cursor: pointer;" onclick="location.href='http://project-voldemort.com';">
		  		<div class="title">
			     	Project Voldemort
			    </div>
			    <div class="subtitle">
					A distributed database
				</div>
			</div>
			<div class="lsidebar">
				<ul>
					<li>
						<a href="design.php">design</a>
					</li>
					<li>
						<a href="http://groups.google.com/group/project-voldemort">discussion</a>
					</li>
					<li>
						<a href="http://code.google.com/p/project-voldemort/downloads/list">download</a>
					</li>
					<li>
						<a href="configuration.php">configuration</a>
					</li>
					<li>
						<a href="/javadoc/client">client javadoc</a>
					</li>
					<li>
						<a href="/javadoc/all">all javadoc</a>
					</li>
					<li>
						<a href="quickstart.php">quickstart</a>
					</li>
					<li>
						<a href="performance.php">performance</a>
					</li>
					<li>
						<a href="http://code.google.com/p/project-voldemort/source/browse/">source</a>
					</li>
					<li>
						<a href="http://code.google.com/p/project-voldemort/issues/list">bugs</a>
					</li>
			</div>
	
			<div class="content">
			